services:
  - type: web
    name: tubi-2026
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: ""
      - key: DB_NAME
        value: tubi_2026
      - key: DB_USER
        value: ""
      - key: DB_PASS
        value: ""
